### ISSUE TITLE
Board component

### ISSUE THREAD

**Issue by shangsuru** [tudaGroup/react-go#6]
Write the component for a 9x9 playing board. Beginning with black, it should be possible to place the stones with alternating colors on the board. Placed stones cannot be removed anymore, but no further game logic should be implemented in this task. The board component should be parameterized with its size. Later we want the player to choose between e.g. a small 9x9 board, a medium 13x13 board and a large 19x19 board.

**Comment by PeanutI3utter** [comment]
The current implementation uses 'react-konva' to draw a canvas, where all board components are drawn. The current implementation uses the Model/View/Controller design Pattern. The Game class is the model, where internal states are kept: the current setting of the field, the history for reverting moves(yet to be implemented), round number and boolean value of currentPlayer == player1(black). The Board Class(View) sets the sizes of the board itself and the fields(children).  it also draws the brown background. The Field class has two purposes: Draw each field with regards to the current game state(is a stone on the current field, how to draw the lines)[View] and input handling(onClick method of class game is passed through board to field)[Controller]. This issue is closely related to issue 4 and 5 due to the choice of its design pattern.
